User.create(email: 'a@com.jp', name: 'a', password: '000000', admin: 'true')
User.create(email: 'b@com.jp', name: 'b', password: '000000')
User.create(email: 'c@com.jp', name: 'c', password: '000000')
User.create(email: 'd@com.jp', name: 'd', password: '000000')
User.create(email: 'e@com.jp', name: 'e', password: '000000')
User.create(email: 'f@com.jp', name: 'f', password: '000000')
User.create(email: 'g@com.jp', name: 'g', password: '000000')
User.create(email: 'h@com.jp', name: 'h', password: '000000')
User.create(email: 'i@com.jp', name: 'i', password: '000000')
User.create(email: 'j@com.jp', name: 'j', password: '000000')
User.create(email: 'k@com.jp', name: 'k', password: '000000')
User.create(email: 'l@com.jp', name: 'l', password: '000000')
User.create(email: 'm@com.jp', name: 'm', password: '000000')
User.create(email: 'n@com.jp', name: 'n', password: '000000')

Group.create(name: a_group, owner_id: 1)
Group.create(name: b_group, owner_id: 2)
Group.create(name: c_group, owner_id: 3)
